@startuml
:
  {{
    salt
      {
        header Sample Page | Contact   
        title $TITLE
        ..
        .
        $CONTENT
        ..
        .
        {#
          Links
          "Sample Page"
          "Contact"
        }
        ..
        footer <&copyright> ACME | Privacy Policy | Terms of Use | Cookie Policy
      }
  }}
;
@enduml
